import type { TrainingProgram, TrainingModule, TrainingPhase, QuizQuestion } from '@/types';

// Giáo trình dựng sẵn (chỉ đọc) — clone vào DB qua "Dùng mẫu". Nội dung rút gọn
// từ cẩm nang điều hành & bộ SOP 4 phòng. Quản lý có thể bổ sung nội dung sau.

let n = 0;
const qid = () => 'q' + (++n).toString(36);
const q = (text: string, options: string[], answer: number, explain?: string): QuizQuestion =>
  ({ id: qid(), q: text, options, answer, explain });

const M = (
  code: string, phase: TrainingPhase, title: string, objective: string,
  opts: Partial<TrainingModule> = {},
): TrainingModule => ({ id: code.toLowerCase(), code, phase, title, objective, ...opts });

// ── GĐ0 hội nhập — chung cho mọi phòng ──────────────────────────────────────
const commonGd0 = (prefix: string): TrainingModule[] => [
  M(`${prefix}-001`, 'gd0', 'Chào mừng & văn hoá Viettours',
    'Hiểu tầm nhìn, giá trị, sơ đồ tổ chức và vị trí của mình trong chuỗi.',
    { estimateDays: 1 }),
  M(`${prefix}-002`, 'gd0', 'Quy tắc ứng xử & bảo mật dữ liệu khách',
    'Nắm quy tắc ứng xử và bảo mật thông tin cá nhân khách (hộ chiếu/visa/tài chính).',
    {
      requiresMentorSignoff: false,
      quiz: [
        q('Dữ liệu cá nhân của khách (hộ chiếu, sao kê) được phép chia sẻ ra ngoài khi nào?',
          ['Khi đồng nghiệp hỏi', 'Không bao giờ nếu không có lý do nghiệp vụ & được phép', 'Khi khách đã thanh toán'], 1),
      ],
    }),
  M(`${prefix}-003`, 'gd0', 'Hệ thống nội bộ (app TCC)',
    'Tự đăng nhập & thao tác cơ bản: báo giá, hồ sơ tour, CRM, quy trình phòng ban.'),
  M(`${prefix}-004`, 'gd0', 'Bức tranh một tour',
    'Vẽ lại vòng đời tour: Sales → Báo giá → Mua hàng → Điều hành → Quyết toán và các điểm bàn giao.'),
];

// ── Track 1: Điều hành nước ngoài (Outbound) ────────────────────────────────
const outbound: TrainingProgram = {
  id: 'seed-outbound', department: 'dh_nuocngoai', roleTarget: 'L2',
  name: 'Điều hành nước ngoài — Nhân viên mới',
  certTitle: 'Qualified Outbound Operator (L2)',
  description: 'Lộ trình 90 ngày vận hành tour outbound multi-country.',
  icon: '🌏', color: '#0d7a6a', version: 1, isPublished: true, isSeed: true,
  modules: [
    ...commonGd0('OB'),
    M('OB-101', 'gd1', 'Vòng đời một tour outbound',
      'Vẽ lại luồng booking → vận hành → quyết toán và 4 điểm bàn giao; nắm các deadline tới hạn.',
      { estimateDays: 1, quiz: [
        q('Tên hành khách trên vé máy bay quốc tế phải khớp 100% với chứng từ nào?',
          ['CCCD', 'Hộ chiếu', 'Giấy khai sinh'], 1),
      ] }),
    M('OB-102', 'gd1', 'Bản đồ thị trường & đối tác land nước ngoài',
      'Nắm 2 tuyến thị trường trọng điểm; biết tra cứu/đánh giá land agent (DMC).',
      { estimateDays: 2, practice: ['Lập bảng so sánh 3 land agent của 1 tuyến (giá, điều khoản, thời gian phản hồi).'] }),
    M('OB-103', 'gd1', 'Vé máy bay quốc tế & nhóm',
      'Đọc hành trình (PNR), hiểu cut-off, tên-theo-hộ-chiếu, hành lý, đổi/huỷ.',
      { estimateDays: 2, practice: ['Soát 1 PNR đoàn mẫu, tìm 5 lỗi gài sẵn.'],
        quiz: [ q('"Cut-off vé đoàn" là gì?',
          ['Giá vé thấp nhất', 'Hạn cuối phải xuất vé & chốt tên', 'Phí huỷ vé'], 1) ] }),
    M('OB-104', 'gd1', 'Visa đoàn & phối hợp phòng Visa',
      'Biết khi nào cần visa, timeline ngược từ ngày bay, ranh giới việc Điều hành vs Visa.',
      { estimateDays: 1, practice: ['Lập timeline ngược cho 1 đoàn Schengen khởi hành sau 45 ngày.'] }),
    M('OB-201', 'gd2', 'Đặt dịch vụ land qua đối tác nước ngoài',
      'Soạn request, nhận confirm, gửi cọc đúng điều khoản (email tiếng Anh).',
      { estimateDays: 3, requiresMentorSignoff: true,
        practice: ['Soạn & gửi chuỗi 4 email (request/chase/amend/cancel) cho 1 land agent.'] }),
    M('OB-202', 'gd2', 'Lập OP Sheet & Itinerary outbound',
      'Tạo OP sheet hoàn chỉnh xong trước T-7; itinerary khách không sai sót.',
      { estimateDays: 3, requiresMentorSignoff: true,
        practice: ['Tự lập OP sheet cho 1 tour outbound thật, dưới giám sát.'],
        quiz: [ q('OP sheet outbound bắt buộc hoàn chỉnh trước mốc nào?',
          ['T-2', 'T-7', 'Ngày khởi hành'], 1) ] }),
    M('OB-203', 'gd2', 'Thanh toán & ngoại tệ NCC',
      'Theo dõi cọc/thanh toán land đúng hạn & đúng loại tiền, tránh mất giữ chỗ.',
      { estimateDays: 2, practice: ['Lập lịch thanh toán cho 1 file outbound multi-country, quy đổi VND.'] }),
    M('OB-204', 'gd2', 'Briefing & bàn giao hồ sơ đoàn',
      'Bàn giao đầy đủ để trưởng đoàn cầm đoàn không phải hỏi lại.',
      { estimateDays: 1, requiresMentorSignoff: true,
        practice: ['Chuẩn bị trọn bộ hồ sơ đoàn cho 1 tour, Senior kiểm.'] }),
    M('OB-301', 'gd3', 'Xử lý sự cố xuyên biên giới',
      'Phản ứng đúng quy trình khi delay/huỷ chuyến, khách ốm/lạc, mất hộ chiếu.',
      { estimateDays: 3, requiresMentorSignoff: true,
        practice: ['Role-play 3 tình huống sự cố; tham gia trực thật 1 tour.'] }),
    M('OB-302', 'gd3', 'Quyết toán tour outbound đa ngoại tệ',
      'Quyết toán đúng, đối chiếu công nợ land agent, tính biên lợi nhuận thực.',
      { estimateDays: 2, requiresMentorSignoff: true,
        practice: ['Tự quyết toán 1 file outbound đã chạy, trình Senior.'] }),
    M('OB-303', 'gd3', 'Đánh giá NCC & cải tiến sau tour',
      'Khép vòng chất lượng: đánh giá land agent, ghi nhận bài học.',
      { estimateDays: 1, practice: ['Viết đánh giá NCC cho tour vừa quyết toán.'] }),
  ],
};

// ── Track 2: Visa ───────────────────────────────────────────────────────────
const visa: TrainingProgram = {
  id: 'seed-visa', department: 'visa', roleTarget: 'L2',
  name: 'Phòng Visa — Nhân viên mới',
  certTitle: 'Qualified Visa Officer (L2)',
  description: 'Lộ trình 90 ngày xử lý hồ sơ visa; tỷ lệ lỗi sau nộp < 1%.',
  icon: '🛂', color: '#0d7a6a', version: 1, isPublished: true, isSeed: true,
  modules: [
    ...commonGd0('VS'),
    M('VS-101', 'gd1', 'Bản đồ thị trường visa',
      'Phân nhóm thị trường dễ → khó (e-visa/ASEAN → Schengen/Mỹ/Anh/Úc).',
      { practice: ['Lập bảng thị trường + độ khó.'] }),
    M('VS-102', 'gd1', 'Cấu trúc một bộ hồ sơ',
      'Hiểu các nhóm giấy tờ: nhân thân, tài chính, công việc, lịch trình, mục đích.'),
    M('VS-103', 'gd1', 'Checklist theo lãnh sự',
      'Lập checklist đúng yêu cầu hiện hành của từng nước.',
      { practice: ['Soạn checklist cho 3 nước.'],
        quiz: [ q('Vì sao phải cập nhật checklist hồ sơ liên tục?',
          ['Để dài hơn', 'Yêu cầu lãnh sự thay đổi thường xuyên', 'Cho đẹp'], 1) ] }),
    M('VS-104', 'gd1', 'Dịch thuật & công chứng',
      'Biết giấy nào cần dịch/công chứng/hợp pháp hoá lãnh sự.'),
    M('VS-105', 'gd1', 'Bảo mật dữ liệu khách',
      'Quy tắc lưu trữ, không lộ thông tin cá nhân.', { requiresMentorSignoff: false }),
    M('VS-201', 'gd2', 'Đánh giá khả năng đậu',
      'Đọc profile (tài chính, lịch sử du lịch, ràng buộc về nước) → tư vấn.',
      { practice: ['Đánh giá 5 ca giả lập.'] }),
    M('VS-202', 'gd2', 'Điền form & đặt lịch hẹn',
      'Điền form khớp 100% giấy tờ; đặt appointment.',
      { requiresMentorSignoff: true, practice: ['Tự làm 1 hồ sơ e-visa/ASEAN thật dưới giám sát.'] }),
    M('VS-203', 'gd2', 'Rà soát 2 lớp',
      'Quy trình NV làm + Senior kiểm cho hồ sơ khó.', { requiresMentorSignoff: true }),
    M('VS-204', 'gd2', 'Giấy tờ tài chính & nhân thân',
      'Kiểm tính hợp lệ sao kê, sổ tiết kiệm, hợp đồng LĐ, giấy tờ hộ tịch.'),
    M('VS-301', 'gd3', 'Thị trường khó',
      'Đặc thù Schengen/Mỹ/Anh/Úc; chuẩn bị phỏng vấn (nếu có).',
      { requiresMentorSignoff: true, practice: ['Chuẩn bị 1 hồ sơ Schengen cùng Senior.'] }),
    M('VS-302', 'gd3', 'Xử lý hồ sơ bị từ chối',
      'Phân tích lý do rớt, hướng nộp lại/khiếu nại.',
      { requiresMentorSignoff: true, practice: ['Phân tích 1 ca rớt thật.'] }),
    M('VS-303', 'gd3', 'Lưu trữ & bàn giao kết quả',
      'Theo dõi tiến trình, thông báo khách, lưu hồ sơ an toàn.'),
  ],
};

// ── Track 3: Điều hành nội địa ──────────────────────────────────────────────
const domestic: TrainingProgram = {
  id: 'seed-domestic', department: 'dh_noidia', roleTarget: 'L2',
  name: 'Điều hành nội địa — Nhân viên mới',
  certTitle: 'Qualified Domestic Operator (L2)',
  description: 'Lộ trình 90 ngày chạy tour nội địa; nền tảng để lên outbound.',
  icon: '🇻🇳', color: '#0d7a6a', version: 1, isPublished: true, isSeed: true,
  modules: [
    ...commonGd0('DN'),
    M('DN-101', 'gd1', 'Vòng đời file tour nội địa',
      'Hiểu luồng Sales → Điều hành → Quyết toán & điểm bàn giao.',
      { practice: ['Đọc & phân tích 3 file mẫu.'] }),
    M('DN-102', 'gd1', 'Mạng lưới NCC nội địa',
      'Nắm KS/xe/HDV/nhà hàng/vé theo các tuyến chính.',
      { practice: ['Lập danh bạ NCC theo tuyến.'] }),
    M('DN-103', 'gd1', 'Đọc booking & mở file', 'Kiểm đủ thông tin, mở file đúng.'),
    M('DN-104', 'gd1', 'Timeline & checklist',
      'Lập timeline ngược, checklist công việc.',
      { practice: ['Lập timeline cho 1 file.'] }),
    M('DN-201', 'gd2', 'Đặt dịch vụ land & đặt cọc',
      'Đặt KS/xe/HDV/nhà hàng/vé, gửi cọc đúng điều khoản.',
      { requiresMentorSignoff: true, practice: ['Đặt dịch vụ cho 1 tour thật.'] }),
    M('DN-202', 'gd2', 'OP sheet & itinerary nội địa',
      'Lập OP sheet hoàn chỉnh trước T-7.',
      { requiresMentorSignoff: true, practice: ['Tự ráp 1 tour nội địa nhỏ.'],
        quiz: [ q('OP sheet phải xong trước mốc nào?', ['T-2', 'T-7', 'Ngày về'], 1) ] }),
    M('DN-203', 'gd2', 'Thực đơn & nhà hàng',
      'Sắp thực đơn theo vùng miền, chống trùng lặp.',
      { practice: ['Lập ma trận thực đơn 1 tour.'] }),
    M('DN-204', 'gd2', 'Briefing HDV & bàn giao',
      'Chuẩn bị bộ hồ sơ đoàn, ký bàn giao.', { requiresMentorSignoff: true }),
    M('DN-301', 'gd3', 'Xử lý sự cố hiện trường',
      'Chậm xe, đổi phòng, khách ốm, thời tiết.',
      { requiresMentorSignoff: true, practice: ['Role-play 3 ca + trực 1 tour thật.'] }),
    M('DN-302', 'gd3', 'Quyết toán & công nợ NCC',
      'Đối chiếu dự toán vs thực chi, chốt công nợ T+7.',
      { requiresMentorSignoff: true, practice: ['Tự quyết toán 1 file.'] }),
    M('DN-303', 'gd3', 'Đánh giá NCC sau tour', 'Chấm chất lượng, đề xuất giữ/bỏ.'),
  ],
};

// ── Track 4: Mua hàng ───────────────────────────────────────────────────────
const procurement: TrainingProgram = {
  id: 'seed-procurement', department: 'muahang', roleTarget: 'L2',
  name: 'Phòng Mua hàng — Nhân viên mới',
  certTitle: 'Qualified Procurement Officer (L2)',
  description: 'Lộ trình 90 ngày đàm phán NCC & kiểm soát giá vốn.',
  icon: '🛒', color: '#0d7a6a', version: 1, isPublished: true, isSeed: true,
  modules: [
    ...commonGd0('MH'),
    M('MH-101', 'gd1', 'Vai trò mua hàng vs điều hành',
      'Hiểu ranh giới bàn giao: Mua hàng lập giá khung ↔ Điều hành đặt theo tour.',
      { quiz: [ q('Phòng Mua hàng chịu trách nhiệm chính việc nào?',
        ['Đặt dịch vụ cho từng tour', 'Đàm phán giá & hợp đồng khung NCC', 'Briefing HDV'], 1) ] }),
    M('MH-102', 'gd1', 'Tìm & phân loại NCC',
      'Nguồn tìm NCC; phân nhóm theo dịch vụ/tuyến.',
      { practice: ['Lập long-list 10 NCC.'] }),
    M('MH-103', 'gd1', 'Cấu trúc giá NET & giá vốn',
      'Hiểu giá NET gồm gì; mùa cao/thấp; phụ phí.',
      { practice: ['Bóc tách 1 bảng giá NET.'] }),
    M('MH-104', 'gd1', 'Tiêu chí đánh giá NCC',
      'Bộ tiêu chí chấm chất lượng & năng lực NCC.',
      { practice: ['Đánh giá 5 NCC.'] }),
    M('MH-201', 'gd2', 'Kỹ năng đàm phán',
      'Chuẩn bị BATNA, mục tiêu giá, nhượng bộ có điều kiện.',
      { requiresMentorSignoff: true, practice: ['Dự 2 buổi đàm phán cùng Senior.'] }),
    M('MH-202', 'gd2', 'Hợp đồng khung & điều khoản',
      'Soạn/đọc HĐ: giá, thanh toán, huỷ, allotment, bồi thường.',
      { requiresMentorSignoff: true, practice: ['Soạn 1 HĐ khung nháp.'] }),
    M('MH-203', 'gd2', 'Allotment & giữ chỗ',
      'Quản lý phòng/ghế giữ trước, release date.',
      { practice: ['Lập bảng allotment 1 KS.'] }),
    M('MH-204', 'gd2', 'Hồ sơ NCC & công nợ',
      'Lập hồ sơ NCC chuẩn; theo dõi công nợ phải trả.',
      { practice: ['Lập hồ sơ 3 NCC.'] }),
    M('MH-301', 'gd3', 'Kiểm soát giá vốn theo mùa',
      'Điều chỉnh giá theo cao/thấp điểm, biến động tỷ giá.',
      { practice: ['Phân tích giá vốn 1 tuyến.'] }),
    M('MH-302', 'gd3', 'Đàm phán & chốt thực tế',
      'Tự đàm phán & chốt 1 nhóm dịch vụ.',
      { requiresMentorSignoff: true, practice: ['Chốt 1 HĐ khung.'] }),
    M('MH-303', 'gd3', 'Đánh giá NCC & rủi ro',
      'Khép vòng chất lượng; quản lý danh sách trắng/đen.'),
  ],
};

export const TRAINING_SEED: TrainingProgram[] = [outbound, visa, domestic, procurement];
